# docker run -p 5000:5000 --name bc1 -dit blockchain python api.py
version: '3'
services:
  bc:
    build: .
    ports:
      - 5000
    # - 80
    command: python -u main.py
    networks:
      - blockchain
networks:
  blockchain:
